const container = document.getElementById("invoice-container");
const params = new URLSearchParams(window.location.search);
const token = params.get("token");

const renderInvoice = (invoice) => {
  const dueDate = invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : "No due date";
  const providerLink = invoice.providerUrl
    ? `<p><strong>Pay online:</strong> <a href="${invoice.providerUrl}" target="_blank" rel="noreferrer noopener">Open payment link</a></p>`
    : "";

  container.innerHTML = `
    <h2>Invoice for ${invoice.recipient}</h2>
    <p><strong>Description:</strong> ${invoice.description}</p>
    <p><strong>Amount:</strong> ${invoice.amount}</p>
    <p><strong>Due date:</strong> ${dueDate}</p>
    ${providerLink}
    <p><strong>Status:</strong> ${invoice.status}</p>
    <p>This invoice link was generated by MJCMusic.</p>
  `;
};

const showError = (message) => {
  container.innerHTML = `
    <h2>Invoice unavailable</h2>
    <p>${message}</p>
  `;
};

if (!token) {
  showError("No invoice token was provided.");
} else {
  fetch(`/api/invoice?token=${encodeURIComponent(token)}`)
    .then(async (response) => {
      if (!response.ok) {
        const error = await response.json().catch(() => ({}));
        throw new Error(error?.error || "Invoice not found.");
      }
      return response.json();
    })
    .then((data) => renderInvoice(data.invoice))
    .catch((error) => showError(error.message));
}
